# -*- coding: utf-8 -*-
"""previsão samsung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kgm3OsYLvCzt6Jc1QVf6S8ipwQKfJYJZ

# Bibliotecas
"""

import yfinance as yf #dados financeiros
import pandas as pd # manipulação de dados
import matplotlib.pyplot as plt # visualização

#machine learning propriamente dito
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_absolute_percentage_error
)
#previsão
from neuralprophet import NeuralProphet

"""# Donwload dos dados"""

#buscar o código no Yahoo Finance
codigo = "005935.KS" #Código da Samsung
inicio = "2015-01-01"
final = "2025-01-01"

#dados historicos (dataframe)

dados = yf.download(codigo, start=inicio, end=final, multi_level_index=False)

#visualizar dados
dados

"""# - Formatação dos dados




"""

# Formatação necessária do NeuralProphet: datas têm que estar em datetime e não podem ser índice
# colunas: 'ds' para data e 'y' minúsculo para valores

# Seleciona a coluna 'Close' e reseta o índice, transformando o DatetimeIndex em uma coluna
dados = dados[["Close"]].reset_index()

# Renomeia as colunas para 'ds' (data) e 'y' (valor)
dados.columns = ["ds","y"]

# Garante que a coluna 'ds' seja do tipo datetime
dados['ds'] = pd.to_datetime(dados['ds'])

dados

"""

*   Treinando modelo

Foi necessário adicionar freq='B' (business days) para que o modelo entendesse que se estavam usando dias úteis e setar a learning_rate=0.001 para driblar o pickling error.

"""

modelo = NeuralProphet() # Remove a definição explícita de loss_func
modelo.fit(dados, freq='B', learning_rate=0.5)
#modelo.fit(dados)

dados_futuros = modelo.make_future_dataframe(dados, periods=365)

previsoes_futuras = modelo.predict(dados_futuros)

previsoes_historicas = modelo.predict(dados)

previsoes_futuras

modelo.plot_components(previsoes_futuras)

"""* Avaliando modelo"""

plt.figure(figsize=(12,6))

plt.plot(
    previsoes_historicas["ds"],
    previsoes_historicas["yhat1"],
    label = "Previsões históricas (2015-2024)",
    c="r",
)

plt.plot(
    previsoes_futuras["ds"],
    previsoes_futuras["yhat1"],
    label = "Previsões futuras (Próximos 365 dias)",
    c="b",
)
plt.plot(dados["ds"],dados["y"], label = "Valores históricos observados (2015-2024)", c="g")
plt.legend()
plt.show()

"""# Avaliando o modelo"""

#Melhor medida para o modelo
r2_score(y_true=previsoes_historicas["y"],y_pred=previsoes_historicas["yhat1"])

mean_absolute_error(y_true=previsoes_historicas["y"],y_pred=previsoes_historicas["yhat1"])

mean_absolute_percentage_error(y_true=previsoes_historicas["y"],y_pred=previsoes_historicas["yhat1"])